export interface IChannelList {
    add: string,
    edit: string,
    remove: string,
    search: string,
    example: string,
    pagItems: string,
    pagPrev: string,
    pagNext: string,
    pagOf: string,
    pagTotal: string,
    tableHeader1: string,
    tableHeader2: string,
    tableHeader3: string,
    tableHeader4: string,
    seeMore: string,
    warning: string,
    confirmMessageSimple: string,
    confirmMessageMultiple: string,
    yes: string,
    deleteComplete: string
}